extract new emacs-window-id script from focus-emacs-frame

diff --git a/bin/focus-emacs-frame b/bin/focus-emacs-frame
--- a/bin/focus-emacs-frame
+++ b/bin/focus-emacs-frame
@@ -28,42 +28,14 @@ check_prereqs () {
     # fi
 }
 
-choose_window_to_focus() {
-    emacs_window_ids=( $(wmctrl -lpx | awk '$4 ~ /emacs/ && $5 ~ /'"$host"'/ { print $1 }') )
-    debug "emacs_window_ids ${emacs_window_ids[@]}"
-
-    if [ "${#emacs_window_ids[*]}" -eq 1 ]; then
-        target_window_id="${emacs_window_ids[0]}"
-    elif [ "${#emacs_window_ids[*]}" -gt 1 ]; then
-        current_desktop=`current-desktop`
-        debug "More than one emacs frame"
-        emacs_window_id=$( wmctrl -lpx | \
-                       awk '$4 ~ /emacs/ &&
-                            $5 ~ /'"$host"'/ &&
-                            $2 == '$current_desktop' { print $1; exit 0 }' )
-        if [ -n "$emacs_window_id" ]; then
-            debug "window_id of emacs on current desktop is $emacs_window_id"
-            target_window_id="$emacs_window_id"
-
-            # The problem here is that emacsclient doesn't tell emacs
-            # server which frame to open the new buffer in.  FIXME: tweak
-            # `server-switch-hook' to do this somehow (env variable?)
-            # http://emacs-fu.blogspot.com/2008/12/opening-emacsclient-windows-on-current.html
-        else
-            debug "No emacs on current desktop; picking any one from ${emacs_window_ids[*]}"
-            target_window_id="${emacs_window_ids[0]}"
-        fi
-    else
-        fatal "No emacs windows found on $DISPLAY"
-    fi
-}
-
 main () {
     host="`hostname`"
     host="${host%%.*}"
 
     check_prereqs
-    choose_window_to_focus
+    if ! target_window_id=$( emacs-window-id ); then
+        fatal "emacs-window-id failed to get target window id"
+    fi
 
     debug "Window name at start: $(current-window-name)"
 
