refuse -e

diff --git a/bin/quick-emacs b/bin/quick-emacs
--- a/bin/quick-emacs
+++ b/bin/quick-emacs
@@ -18,6 +18,11 @@ if [ "$1" = '--bg-if-poss' ]; then
     shift
 fi
 
+if echo "$*" | egrep -q '(^| )-e( |$)'; then
+    echo "-e would only work with emacsclient, not with new-emacs; aborting." >&2
+    exit 1
+fi
+
 debug () {
     :
     echo "$*" >&2
