cope with multiple emacs windows

diff --git a/bin/switch-feed-emacs b/bin/switch-feed-emacs
--- a/bin/switch-feed-emacs
+++ b/bin/switch-feed-emacs
@@ -5,13 +5,18 @@ if [ -z "$DISPLAY" ]; then
     exit 1
 fi
 
-if ! wmctrl -a 'emacs@'; then
-    echo "$0: wmctrl failed" >&2
-    if ! wmctrl -l | grep 'emacs@'; then
-        echo "No windows matching 'emacs@' found; maybe you have >1 frame open?" >&2
-    fi
+if ! which wmctrl >/dev/null 2>&1; then
+    echo "$0: wmctrl not found; aborting." >&2
     exit 1
 fi
+
+winid=$( wmctrl -lpx | awk '$4 ~ /emacs/ {id = $1} END {print id}' )
+if [ -z "$winid" ]; then
+    echo "$0: wmctrl failed to find an emacs window" >&2
+    exit 1
+fi
+
+wmctrl -i -a "$winid"
 
 # It seems there is some kind of timing issue which requires this
 # sleep - probably we have to ensure that wmctrl has finished
