$GCONFTOOL

diff --git a/.cfg-post.d/emacs b/.cfg-post.d/emacs
--- a/.cfg-post.d/emacs
+++ b/.cfg-post.d/emacs
@@ -3,6 +3,8 @@
 version=$( emacs --version | \
              perl -ne '/^\s*(GNU |X)Emacs (\d+\.\d+)/ && print "$2"' )
 
+GCONFTOOL=gconftool-2
+
 cd
 [ -e .eid ]            || ln -sf .emacs.d/init.d .eid
 [ -e .as-bindings.el ] && rm .as-bindings.el
@@ -12,20 +14,22 @@ cd
 ln -sf lib/emacs/init/GNU_Emacs/as-custom-$version.el .as-custom.el
 
 [ -e .msf-abbrevs ] || \
-  ln -sf lib/emacs/minor-modes/msf-abbrev/mode-abbrevs .msf-abbrevs
+    ln -sf lib/emacs/minor-modes/msf-abbrev/mode-abbrevs .msf-abbrevs
 
-if which gconftool-2 >/dev/null 2>&1; then
-  gconftool-2 -s /desktop/gnome/url-handlers/annotation/command \
-    -t string 'org-annotation-helper %s'
-  gconftool-2 -s /desktop/gnome/url-handlers/annotation/enabled -t bool yes
+if ! which $GCONFTOOL >/dev/null 2>&1; then
+    echo "WARNING: can't find $GCONFTOOL; url-handlers will not be set" >&2
+else
+    $GCONFTOOL -s /desktop/gnome/url-handlers/annotation/command \
+               -t string 'org-annotation-helper %s'
+    $GCONFTOOL -s /desktop/gnome/url-handlers/annotation/enabled -t bool yes
 
-  gconftool-2 -s /desktop/gnome/url-handlers/remember/command \
-    -t string 'org-annotation-helper %s'
-  gconftool-2 -s /desktop/gnome/url-handlers/remember/enabled -t bool yes
+    $GCONFTOOL -s /desktop/gnome/url-handlers/remember/command \
+               -t string 'org-annotation-helper %s'
+    $GCONFTOOL -s /desktop/gnome/url-handlers/remember/enabled -t bool yes
 
-  gconftool-2 -s /desktop/gnome/url-handlers/org-protocol/command \
-    -t string 'emacsclient %s'
-  gconftool-2 -s /desktop/gnome/url-handlers/org-protocol/enabled -t bool yes
+    $GCONFTOOL -s /desktop/gnome/url-handlers/org-protocol/command \
+               -t string 'quick-emacs %s'
+    $GCONFTOOL -s /desktop/gnome/url-handlers/org-protocol/enabled -t bool yes
 fi
 
 # Put this last as it's most likely to fail.
