move >&2 to just after echo

diff --git a/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/diex b/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/diex
--- a/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/diex
+++ b/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/diex
@@ -1,2 +1,2 @@
-echo "<field "ERROR">" >&2
+echo >&2 "<field "ERROR">"
 exit 1
diff --git a/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/errx b/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/errx
--- a/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/errx
+++ b/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/errx
@@ -1,2 +1,2 @@
-echo "ERROR: <cursor>"
+echo >&2 "ERROR: <cursor>"
 exit 1
diff --git a/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/ifdiex b/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/ifdiex
--- a/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/ifdiex
+++ b/lib/emacs/minor-modes/msf-abbrev/mode-abbrevs/sh-mode/ifdiex
@@ -1,4 +1,4 @@
 if <field "expression">; then
-echo "<field "ERROR">" >&2
+echo >&2 "<field "ERROR">"
 exit 1
 fi
