yasnippet: sh-mode improvements

diff --git a/.emacs.d/snippets/sh-mode/flow control/ifdie b/.emacs.d/snippets/sh-mode/flow control/ifdie
--- a/.emacs.d/snippets/sh-mode/flow control/ifdie
+++ b/.emacs.d/snippets/sh-mode/flow control/ifdie
@@ -1,8 +1,8 @@
 # -*- mode: snippet -*-
 # name: ifdie
-# key: ifdie
+# key: ifd
 # --
 if ${1:expression}; then
-echo >&2 "${2:ERROR}"
-exit 1
+    echo >&2 "${2:ERROR}"
+    exit 1
 fi
